### ISSUE TITLE
Dashboard: Global dashboard is broken

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#5195]
## Describe the bug

Global dashboard is broken, due console errors. Page does not render data.
## To Reproduce

1. Go to https://qa.commonwealth.im/dashboard/global
2. Observe

## Expected behavior

We should display global dashboard with rendered data

## Additional context

```
3152.9b253f59.js:2  TypeError: n.forEach is not a function
    at app.3476af20.js:98:497655
    at Array.forEach (<anonymous>)
    at g (app.3476af20.js:98:497603)
    at _s (3152.9b253f59.js:2:2730453)
    at xu (3152.9b253f59.js:2:2787412)
    at bl (3152.9b253f59.js:2:2776394)
    at yl (3152.9b253f59.js:2:2776322)
    at gl (3152.9b253f59.js:2:2776185)
    at ol (3152.9b253f59.js:2:2772992)
```
Image:
https://app.screencast.com/cHbgk1ftN8dsH

**Comment by jnaviask** [comment]
Looks like behavior was caused by #5130. Assigning @martins87 for a quick fix.
